export interface History {
    originalText: string | null;
    updatedText: string | null;
    timeStamp: string;
  }

export const historiesSubscription: History[] = [
    //Can be later populated from an API subscription
    {originalText: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus lacinia nulla nisi, at convallis turpis blandit id. Curabitur interdum, ipsum non malesuada cursus, purus leo pharetra nisi, eget fermentum purus magna vel justo. Integer consectetur dui sit amet dolor scelerisque, sed iaculis magna aliquam. Proin at lorem sed justo tincidunt varius et nec lorem. Donec a erat mollis, tincidunt lorem a, cursus neque. Nunc vitae suscipit purus. Integer tincidunt, ante ac scelerisque tempor, dui mi pharetra ex, id rutrum metus eros sed elit. Aliquam erat volutpat. Mauris volutpat, nisl ut cursus dapibus, lectus lorem venenatis urna, non posuere dui turpis ac elit", updatedText: 'SomeReplacedWord ipsum dolor sit amet, consectetur adipiscing elit. Vivamus lacinia nulla nisi, at convallis turpis blandit id. Curabitur interdum, ipsum non malesuada cursus, purus leo pharetra nisi, eget fermentum purus magna vel justo. Integer consectetur dui sit amet dolor scelerisque, sed iaculis magna aliquam. Proin at SomeReplacedWord sed justo tincidunt varius et nec SomeReplacedWord. Donec a erat mollis, tincidunt SomeReplacedWord a, cursus neque. Nunc vitae suscipit purus. Integer tincidunt, ante ac scelerisque tempor, dui mi pharetra ex, id rutrum metus eros sed elit. Aliquam erat volutpat. Mauris volutpat, nisl ut cursus dapibus, lectus SomeReplacedWord venenatis urna, non posuere dui turpis ac elit', timeStamp: '2025-06-02 14:31'},
    {originalText: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus lacinia nulla nisi, at convallis turpis blandit id. Curabitur interdum, ipsum non malesuada cursus, purus leo pharetra nisi, eget fermentum purus magna vel justo. Integer consectetur dui sit amet dolor scelerisque, sed iaculis magna aliquam. Proin at lorem sed justo tincidunt varius et nec lorem. Donec a erat mollis, tincidunt lorem a, cursus neque. Nunc vitae suscipit purus. Integer tincidunt, ante ac scelerisque tempor, dui mi pharetra ex, id rutrum metus eros sed elit. Aliquam erat volutpat. Mauris volutpat, nisl ut cursus dapibus, lectus lorem venenatis urna, non posuere dui turpis ac elit", updatedText: 'SomeReplacedWord ipsum dolor sit amet, consectetur adipiscing elit. Vivamus lacinia nulla nisi, at convallis turpis blandit id. Curabitur interdum, ipsum non malesuada cursus, purus leo pharetra nisi, eget fermentum purus magna vel justo. Integer consectetur dui sit amet dolor scelerisque, sed iaculis magna aliquam. Proin at SomeReplacedWord sed justo tincidunt varius et nec SomeReplacedWord. Donec a erat mollis, tincidunt SomeReplacedWord a, cursus neque. Nunc vitae suscipit purus. Integer tincidunt, ante ac scelerisque tempor, dui mi pharetra ex, id rutrum metus eros sed elit. Aliquam erat volutpat. Mauris volutpat, nisl ut cursus dapibus, lectus SomeReplacedWord venenatis urna, non posuere dui turpis ac elit', timeStamp: '2025-05-02 12:31'},
    {originalText: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus lacinia nulla nisi, at convallis turpis blandit id. Curabitur interdum, ipsum non malesuada cursus, purus leo pharetra nisi, eget fermentum purus magna vel justo. Integer consectetur dui sit amet dolor scelerisque, sed iaculis magna aliquam. Proin at lorem sed justo tincidunt varius et nec lorem. Donec a erat mollis, tincidunt lorem a, cursus neque. Nunc vitae suscipit purus. Integer tincidunt, ante ac scelerisque tempor, dui mi pharetra ex, id rutrum metus eros sed elit. Aliquam erat volutpat. Mauris volutpat, nisl ut cursus dapibus, lectus lorem venenatis urna, non posuere dui turpis ac elit", updatedText: 'SomeReplacedWord ipsum dolor sit amet, consectetur adipiscing elit. Vivamus lacinia nulla nisi, at convallis turpis blandit id. Curabitur interdum, ipsum non malesuada cursus, purus leo pharetra nisi, eget fermentum purus magna vel justo. Integer consectetur dui sit amet dolor scelerisque, sed iaculis magna aliquam. Proin at SomeReplacedWord sed justo tincidunt varius et nec SomeReplacedWord. Donec a erat mollis, tincidunt SomeReplacedWord a, cursus neque. Nunc vitae suscipit purus. Integer tincidunt, ante ac scelerisque tempor, dui mi pharetra ex, id rutrum metus eros sed elit. Aliquam erat volutpat. Mauris volutpat, nisl ut cursus dapibus, lectus SomeReplacedWord venenatis urna, non posuere dui turpis ac elit', timeStamp: '2025-04-02 09:50'}
]