// Interface representing the history of text replacements
export interface History {
    originalText: string | undefined; // The original text before replacement
    updatedText: string | undefined; // The text after replacements
    timeStamp: string; // Timestamp of when the replacement occurred
}

//Interface representing the Integrated Services
export interface Service {
  serviceName: string | null; // The display name of the service
  serviceShortDesc: string | null; // A short description of the service
  functionName: string; // Internal function identifier for the service
  features: Array<string>; // List of features supported by the service
  icon: string; // The associated icon (Ant Design icon name)
  active: boolean; // Whether the service is currently active
}

export const historiesSubscription: History[] = [
    //Can be later populated from an API subscription
    {originalText: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus lacinia nulla nisi, at convallis turpis blandit id. Curabitur interdum, ipsum non malesuada cursus, purus leo pharetra nisi, eget fermentum purus magna vel justo. Integer consectetur dui sit amet dolor scelerisque, sed iaculis magna aliquam. Proin at lorem sed justo tincidunt varius et nec lorem. Donec a erat mollis, tincidunt lorem a, cursus neque. Nunc vitae suscipit purus. Integer tincidunt, ante ac scelerisque tempor, dui mi pharetra ex, id rutrum metus eros sed elit. Aliquam erat volutpat. Mauris volutpat, nisl ut cursus dapibus, lectus lorem venenatis urna, non posuere dui turpis ac elit", updatedText: 'SomeReplacedWord ipsum dolor sit amet, consectetur adipiscing elit. Vivamus lacinia nulla nisi, at convallis turpis blandit id. Curabitur interdum, ipsum non malesuada cursus, purus leo pharetra nisi, eget fermentum purus magna vel justo. Integer consectetur dui sit amet dolor scelerisque, sed iaculis magna aliquam. Proin at SomeReplacedWord sed justo tincidunt varius et nec SomeReplacedWord. Donec a erat mollis, tincidunt SomeReplacedWord a, cursus neque. Nunc vitae suscipit purus. Integer tincidunt, ante ac scelerisque tempor, dui mi pharetra ex, id rutrum metus eros sed elit. Aliquam erat volutpat. Mauris volutpat, nisl ut cursus dapibus, lectus SomeReplacedWord venenatis urna, non posuere dui turpis ac elit', timeStamp: '2025-02-06 14:31'},
    {originalText: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus lacinia nulla nisi, at convallis turpis blandit id. Curabitur interdum, ipsum non malesuada cursus, purus leo pharetra nisi, eget fermentum purus magna vel justo. Integer consectetur dui sit amet dolor scelerisque, sed iaculis magna aliquam. Proin at lorem sed justo tincidunt varius et nec lorem. Donec a erat mollis, tincidunt lorem a, cursus neque. Nunc vitae suscipit purus. Integer tincidunt, ante ac scelerisque tempor, dui mi pharetra ex, id rutrum metus eros sed elit. Aliquam erat volutpat. Mauris volutpat, nisl ut cursus dapibus, lectus lorem venenatis urna, non posuere dui turpis ac elit", updatedText: 'SomeReplacedWord ipsum dolor sit amet, consectetur adipiscing elit. Vivamus lacinia nulla nisi, at convallis turpis blandit id. Curabitur interdum, ipsum non malesuada cursus, purus leo pharetra nisi, eget fermentum purus magna vel justo. Integer consectetur dui sit amet dolor scelerisque, sed iaculis magna aliquam. Proin at SomeReplacedWord sed justo tincidunt varius et nec SomeReplacedWord. Donec a erat mollis, tincidunt SomeReplacedWord a, cursus neque. Nunc vitae suscipit purus. Integer tincidunt, ante ac scelerisque tempor, dui mi pharetra ex, id rutrum metus eros sed elit. Aliquam erat volutpat. Mauris volutpat, nisl ut cursus dapibus, lectus SomeReplacedWord venenatis urna, non posuere dui turpis ac elit', timeStamp: '2025-05-02 12:31'},
    {originalText: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus lacinia nulla nisi, at convallis turpis blandit id. Curabitur interdum, ipsum non malesuada cursus, purus leo pharetra nisi, eget fermentum purus magna vel justo. Integer consectetur dui sit amet dolor scelerisque, sed iaculis magna aliquam. Proin at lorem sed justo tincidunt varius et nec lorem. Donec a erat mollis, tincidunt lorem a, cursus neque. Nunc vitae suscipit purus. Integer tincidunt, ante ac scelerisque tempor, dui mi pharetra ex, id rutrum metus eros sed elit. Aliquam erat volutpat. Mauris volutpat, nisl ut cursus dapibus, lectus lorem venenatis urna, non posuere dui turpis ac elit", updatedText: 'SomeReplacedWord ipsum dolor sit amet, consectetur adipiscing elit. Vivamus lacinia nulla nisi, at convallis turpis blandit id. Curabitur interdum, ipsum non malesuada cursus, purus leo pharetra nisi, eget fermentum purus magna vel justo. Integer consectetur dui sit amet dolor scelerisque, sed iaculis magna aliquam. Proin at SomeReplacedWord sed justo tincidunt varius et nec SomeReplacedWord. Donec a erat mollis, tincidunt SomeReplacedWord a, cursus neque. Nunc vitae suscipit purus. Integer tincidunt, ante ac scelerisque tempor, dui mi pharetra ex, id rutrum metus eros sed elit. Aliquam erat volutpat. Mauris volutpat, nisl ut cursus dapibus, lectus SomeReplacedWord venenatis urna, non posuere dui turpis ac elit', timeStamp: '2025-04-02 09:50'}
]

export const servicesSubscription: Service[] = [
    //Can be later populated from an API subscription
  {serviceName: 'Find & Replace Tool', serviceShortDesc: 'Find and Replace single or multiple occurences of text.', features: ['Autosave', 'Show Live Changes', 'Regex Support', 'History of Replacements'], functionName: 'frl', icon: 'minus-circle', active: true},
  {serviceName: 'Text Comparator', serviceShortDesc: 'Compare two different texts and get various insights', features: ['Show Hits in Green', 'Show Misses in Red', 'History of Comparisons'], functionName: 'tcr', icon: 'question-circle', active: false}
]